# This is a basic workflow to help you get started with Actions

name: containerscanning

on: [push]
env:
  CI_REGISTRY_IMAGE: registry.gitlab.com/sakkoub-group/cicd-workshop/sample-nodejsexpress
  
jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build --pull -t  '${{ env.CI_REGISTRY_IMAGE }}' .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: "registry.gitlab.com/sakkoub-group/cicd-workshop/sample-nodejsexpress"
    
    - uses: Azure/docker-login@v1
      with:
        login-server: "registry.gitlab.com" # ${{ env.CONTAINER_REGISTRY }}
        username: "gitlab+deploy-token-1196282" # ${{ secrets.REGISTRY_USERNAME }}
        password: "NrUBiH9J9m4VY1k_ocD5"
    - run: docker login -u "registry.gitlab.com" -p "NrUBiH9J9m4VY1k_ocD5" registry.gitlab.com
    - run: docker push "registry.gitlab.com/sakkoub-group/cicd-workshop/sample-nodejsexpress"
