# This is a basic workflow to help you get started with Actions

name: containerscanning

on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build --pull -t registry.gitlab.com registry.gitlab.com/sakkoub-group/cicd-workshop/sample-nodejsexpress .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: "registry.gitlab.com registry.gitlab.com/sakkoub-group/cicd-workshop/sample-nodejsexpress"
    
    - uses: Azure/docker-login@v1
      with:
        login-server: "registry.gitlab.com" # ${{ env.CONTAINER_REGISTRY }}
        username: "gitlab-ci-token" # ${{ secrets.REGISTRY_USERNAME }}
        password: "NrUBiH9J9m4VY1k_ocD5"
    
    - run: docker push "registry.gitlab.com registry.gitlab.com/sakkoub-group/cicd-workshop/sample-nodejsexpress"
